runtime: python39

instance_class: F1

env_variables:
  PYTHON_VERSION: "3.9"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT web_app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

volumes:
- name: data
  size_gb: 1
  mount_point: /app/classified_documents 