services:
  - type: web
    name: doc-class
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/classified_documents
      sizeGB: 1
    autoDeploy: true 