services:
  - type: web
    name: doc-class
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
    autoDeploy: true 